apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  generateName: icici-pr-
spec:
  pipelineRef:
    name: build-and-deploy-pipeline
  resources:
    - name: git-source
      resourceRef:
        name: icici-git
  params:
    - name: pathToYamlFile
      value: "knative/icici.yaml"
    - name: imageUrl
      value: de.icr.io/icici-demo/fundtransfer  
    - name: imageTag
      value: "1.0"
  serviceAccountName: pipeline-account